// rest-countries-api-with-color-theme-switcher-react-ts/src/app/components/molecules/Card.tsx
import React from "react";
import { useSelector } from "react-redux";
import { darkTheme } from "../../../store/modules/darkThemeSlice";
import { Country } from "../../../types/country.interface";

interface CardProps {
  countryData: Country;
}

export function Card({ countryData }: CardProps) {
  const isDarkTheme = useSelector(darkTheme);
  const cardClassName = `card ${isDarkTheme ? "card--darkTheme" : ""}`;
  const cardDescClassName = `card__desc ${
    isDarkTheme ? "card__desc--darkTheme" : ""
  }`;
  return (
    <div className={cardClassName}>
      <img src={countryData.flag} alt="Flag" />
      <div className={cardDescClassName}>
        <h2>{countryData.name}</h2>
        <h3>Population: {countryData.population}</h3>
        <h3>Region: {countryData.region}</h3>
        <h3>Capital: {countryData.capital}</h3>
      </div>
    </div>
  );
}

// rest-countries-api-with-color-theme-switcher-master/src/components/molecules/Card.vue
<template>
  <div :class="[isDarkTheme ? 'card--darkTheme' : '', 'card']">
    <img :src="countryData.flag" />
    <div :class="[isDarkTheme ? 'card__desc--darkTheme' : '', 'card__desc']">
      <h2>{{ countryData.name }}</h2>
      <h3>Population: {{ countryData.population }}</h3>
      <h3>Region: {{ countryData.region }}</h3>
      <h3>Capital: {{ countryData.capital }}</h3>
    </div>
  </div>
</template>

<script lang="ts">
  import { Country } from '@/types/country.interface';
  import { defineComponent, PropType } from 'vue';
  import { mapState, useStore } from 'vuex';
  export default defineComponent({
    setup() {
      const store = useStore();
      return { store };
    },
    computed: {
      ...mapState(['isDarkTheme'])
    },
    props: { countryData: { type: Object as PropType<Country>, required: true } }
  });
</script>

<style></style>
