// rest-countries-api-with-color-theme-switcher-master/src/components/organisms/CardContainer.vue
<template>
  <div :class="[isDarkTheme ? 'cardContainer--darkTheme' : '', 'cardContainer']">
    <card v-for="(countryData, index) in countryDatas" :countryData="countryData" :key="index" />
  </div>
</template>

<script lang="ts">
  import Card from '../molecules/Card.vue';
  import { defineComponent } from 'vue';
  import { mapState, useStore } from 'vuex';
  export default defineComponent({
    components: {
      Card
    },
    setup() {
      const store = useStore();
      return { store };
    },
    props: { countryDatas: { type: Array, required: true } },
    computed: {
      ...mapState(['isDarkTheme'])
    }
  });
</script>

<style></style>

// rest-countries-api-with-color-theme-switcher-react-ts/src/app/components/organisms/CardContainer.tsx
import React from "react";
import { useSelector } from "react-redux";
import { darkTheme } from "../../../store/modules/darkThemeSlice";
import { Country } from "../../../types/country.interface";
import { Card } from "../molecules/Card";
import { FilterField } from "../organisms/FilterField";

interface CardContainerProps {
  countryDatas: Country[];
}

export function CardContainer({ countryDatas }: CardContainerProps) {
  const isDarkTheme = useSelector(darkTheme);
  const cardContainerClassName = `cardContainer ${
    isDarkTheme ? "cardContainer--darkTheme" : ""
  }`;
  return (
    <div>
      <FilterField />
      <div className={cardContainerClassName}>
        {countryDatas.map((country, index) => {
          return <Card countryData={country} key={index} />;
        })}
      </div>
    </div>
  );
}
