// rest-countries-api-with-color-theme-switcher-master/src/components/molecules/NavBar.vue
<template>
  <div :class="[isDarkTheme ? 'nav--darkTheme' : '', 'nav']">
    <h2>Where in the world?</h2>
    <DarkthemeToggle />
  </div>
</template>

<script lang="ts">
  import DarkthemeToggle from '../atoms/DarkthemeToggle.vue';
  import { defineComponent } from 'vue';
  import { mapState, useStore } from 'vuex';
  export default defineComponent({
    setup() {
      const store = useStore();
      return { store };
    },
    components: {
      DarkthemeToggle
    },
    computed: {
      ...mapState(['isDarkTheme'])
    }
  });
</script>

// rest-countries-api-with-color-theme-switcher-react-ts/src/app/components/molecules/NavBar.tsx
import React from "react";
import { useSelector } from "react-redux";
import { darkTheme } from "../../../store/modules/darkThemeSlice";
import { DarkThemeToggle } from "../atoms/darkThemeToggle/DarkThemeToggle";

export function Navbar() {
  const isDarkTheme = useSelector(darkTheme);
  const navClassName = `nav ${isDarkTheme ? "nav--darkTheme" : ""}`;
  return (
    <div className={navClassName}>
      <h2>Where in the world?</h2>
      <DarkThemeToggle />
    </div>
  );
}
